region                       = "us-east-1"
az1                          = "us-east-1a"
az2                          = "us-east-1b"
vpc_cidr                     = "10.0.0.0/16"
public_subnet_az1_cidr       = "10.0.1.0/24"
public_subnet_az2_cidr       = "10.0.2.0/24"
private_app_subnet_az1_cidr  = "10.0.3.0/24"
private_app_subnet_az2_cidr  = "10.0.4.0/24"
private_data_subnet_az1_cidr = "10.0.5.0/24"
private_data_subnet_az2_cidr = "10.0.6.0/24"
ami_type                     = "ami-0ecb62995f68bb549"
instance_type                = "t3.micro"
db_name                      = "edoc"
#db_username                  = "user"
#db_password                  = "password"
bastion_public_key_path = "keys/edoc_bastion.pub"

